export const appLanguages = [
  ['en', 'English'],
  ...Object.entries({
    ar: 'العربية',
    az: 'Azərbaycanca',
    bn: 'বাংলা',
    cs: 'Čeština',
    da: 'Dansk',
    de: 'Deutsch',
    el: 'Ελληνικά',
    es: 'Español',
    fa: 'فارسی',
    fr: 'Français',
    hi: 'हिन्दी',
    hr: 'Hrvatski',
    ht: 'Kreyòl Ayisyen',
    hu: 'Magyar',
    id: 'Bahasa Indonesia',
    it: 'Italiano',
    ja: '日本語',
    ko: '한국어',
    nb: 'Norsk bokmål',
    nl: 'Nederlands',
    or: 'ଓଡ଼ିଆ',
    pl: 'Polski',
    'pt-BR': 'Português (Brasil)',
    'pt-PT': 'Português (Portugal)',
    ro: 'Română',
    ru: 'Русский',
    sv: 'Svenska',
    ta: 'தமிழ்',
    th: 'ภาษาไทย',
    tr: 'Türkçe',
    uk: 'Українська',
    uz: 'Oʻzbekcha',
    vi: 'Tiếng Việt',
    'zh-CN': '简体中文',
    'zh-TW': '繁體中文',
  }).sort((a, b) => a[1].localeCompare(b[1])),
];
