/**
 * Splitting a published changelog at the version that is installed.
 *
 * The document is one section per version, generated by windhawk-mods' deploy.ts:
 *
 *     ## 1.2.1 ([June 4, 2024](https://github.com/.../commit/abc123))
 *
 *     - Fixed the thing.
 *
 * so the installed version's own heading is the line where "what this update
 * brings" ends and "what the user already has" begins.
 *
 * This parses a document another repository generates, so both ways of failing to
 * find that line fall back to the whole document: a blank tab is the worse answer.
 */

export type ChangelogSplit = {
  // The entries above the installed version's heading - the whole document when
  // there is no heading to split at.
  newEntries: string;
  // The installed version's heading and everything below it, or empty when the
  // whole document counts as new.
  olderEntries: string;
};

// A version section heading: two hashes (not three, which is a heading inside an
// entry) and the version as the first token, ending at the date link after it.
const HEADING_PATTERN = /^##(?!#)[^\S\r\n]*([^\s(]+)/gm;

type Heading = { index: number; version: string };

function headingsOf(changelog: string): Heading[] {
  const pattern = new RegExp(HEADING_PATTERN);
  const headings: Heading[] = [];
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(changelog)) !== null) {
    headings.push({ index: match.index, version: match[1] });
  }
  return headings;
}

/**
 * Split `changelog` into the entries newer than `installedVersion` and the rest.
 *
 * The whole document is returned as new, with no remainder, when the installed
 * version has no section of its own - a version older than the published history,
 * a renamed mod, a hand-written `changelog_override` - and when its section is
 * already the newest one, which means the repository moved the source without
 * bumping the version and the diff is what carries the detail.
 */
export function changelogSince(
  changelog: string,
  installedVersion?: string
): ChangelogSplit {
  const whole: ChangelogSplit = { newEntries: changelog, olderEntries: '' };
  if (!installedVersion) {
    return whole;
  }

  const headings = headingsOf(changelog);
  const installedAt = headings.findIndex(
    (heading) => heading.version === installedVersion
  );
  if (installedAt <= 0) {
    return whole;
  }

  const splitAt = headings[installedAt].index;
  return {
    newEntries: changelog.slice(0, splitAt).trimEnd(),
    olderEntries: changelog.slice(splitAt),
  };
}
